all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-35-164-96-185.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-54-201-88-180.us-west-2.compute.amazonaws.com
